@startuml classDiagram

class Cliente {
    - id: int
    - cpf: string
    - nome: string
    - contato: string
    - aparelhos: Aparelho[]
}

class Aparelho {
    - id: int
    - modelo: string
    - descricaoProblema: string
    - dataEntrada: Date
    - status: string
    - solucao: string
    - valorServico: float
    - dataSaida: Date
    - senha: string
    - imei: string
}

Cliente " 1 " --> " * " Aparelho
Aparelho " 1 " --> " 1 " Cliente

class Sistema {
    + cadastrarCliente(cpf: string, nome: string, contato: string): Cliente
    + cadastrarAparelho(modelo: string, descricaoProblema: string, dataEntrada: Date, status: string,
     solucao: string, valorServico: float, dataSaida: Date, senha: string, imei: string): Aparelho
    + editarCliente(cliente: Cliente): void
    + editarAparelho(aparelho: Aparelho): void
    + excluirCliente(cliente: Cliente): void
    + excluirAparelho(aparelho: Aparelho): void
    + buscarClientePorNome(nome: string): Cliente[]
    + buscarClientePorCpf(cpf: string): Cliente
    + buscarAparelhoPorId(id: int): Aparelho
    + buscarAparelhoPorModelo(modelo: string): Aparelho[]
    + exportarDados(): void
    + importarDados(): void
}

@enduml
